article/urls.py
from django.urls import path
from .views import *

app_name = 'article'

urlpatterns = [
    path('', articles_list, name='list'),
    path('dashboard/', my_articles, name='dashboard'),
    path('detail/<int:id>', article_detail, name='detail'),
    path('create/', article_create, name='create'),
    path('update/<int:id>', article_update, name='update'),
    path('delete/<int:id>', article_delete, name='delete'),
    path('comment-create/<int:id>', comment_create, name='comment-create'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from home.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('about/', about_view, name='about'),
    path('articles/', include('article.urls')),
    path('users/', include('user.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import *

app_name = 'user'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
class Article(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='articles', blank=True, null=True)

    def __str__(self):
        return f'{self.title} | {self.author}'
    
class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="comments")
    author = models.CharField(max_length=50)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
            return f"{self.author} | {self.content}"

home/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta: 
        model = Article
        fields = ['title', 'content', 'image']

user/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(max_length=30, label="Username")
    password = forms.CharField(max_length=10, label="Password", widget=forms.PasswordInput)
    

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=30, label="Username")
    password = forms.CharField(max_length=10, label="Password", widget=forms.PasswordInput)
    confirm = forms.CharField(max_length=10, label="Confirm password", widget=forms.PasswordInput)
    
    def clean(self):
        username = self.cleaned_data["username"]
        password = self.cleaned_data["password"]
        confirm = self.cleaned_data["confirm"]
        
        
        if password and confirm and password != confirm:
            raise forms.ValidationError("Passwords doesn't match!!")
        
        values = {
            "username": username,
            "password": password
        }
        
        return values

article/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article, Comment
from .forms import ArticleForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse


# Create your views here.
@login_required(login_url="user:login")
def articles_list(request):
    keyword = request.GET.get('keyword')

    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
    else:
        articles = Article.objects.all()
    return render(request, 'articles_list.html', { 'articles': articles })


@login_required(login_url="user:login")  
def my_articles(request):
    articles = Article.objects.filter(author = request.user)
    return render(request, 'dashboard.html', {'articles': articles})  


@login_required(login_url="user:login") 
def article_detail(request, id):
    article = get_object_or_404(Article, id=id)
    comments = article.comments.all

    context = {
        'article': article,
        'comments': comments,
    }
    return render(request, 'article-detail.html', context)


@login_required(login_url="user:login")  
def article_create(request):
    form = ArticleForm(request.POST or None, request.FILES or None)
    context = {'form': form}

    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()

        messages.success(request, 'Article created successfully')
        return redirect('article:dashboard')
    
    return render(request, 'article-create.html', context)


@login_required(login_url='user:login')
def article_update(request, id):
    article = get_object_or_404(Article, id=id)
    form = ArticleForm(request.POST or None, request.FILES or None, instance=article)
    context = {"form": form}

    if form.is_valid():
        article.save()
        messages.success(request, 'Article updated successfully')
        return redirect('article:dashboard')

    return render(request, "article-update.html", context)


@login_required(login_url='user:login')
def article_delete(request, id):
    article = get_object_or_404(Article, id=id)
    article.delete()
    messages.success(request, 'Article deleted successfully')
    return redirect('article:dashboard')


@login_required(login_url='user:login')
def comment_create(request, id):
    article = get_object_or_404(Article, id=id)

    if request.method == "POST":
        comment_author = request.POST.get('comment_author')
        comment_content = request.POST.get('comment_content')

        comment = Comment(author = comment_author, content = comment_content)
        comment.article = article
        comment.save()
        messages.success(request, "Comment added successfully")

    return redirect(reverse("article:detail", kwargs={"id":id}))

home/views.py
from django.shortcuts import render

# Create your views here.
def home_view(request):
    return render(request, 'index.html')

def about_view(request):
    return render(request, 'about.html')

user/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm, LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages

# Create your views here.
def login_view(request):
    form = LoginForm(request.POST or None)
    
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        
        user = authenticate(username=username, password=password)
        
        if user is not None:
            login(request, user)
            messages.success(request, 'Successfull login')
            return redirect('home')
    
    context = { "form": form }
    return render(request, "login.html", context)


def register_view(request):
    form = RegisterForm(request.POST or None)

    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')

        new_user = User(username=username, password=password)
        new_user.save()

        login(request, new_user)
        messages.success(request, 'Successfull login')  

        return redirect('home')
    

    context = { 'form': form }
    return render(request, 'register.html', context)



def logout_view(request):
    logout(request)
    return redirect("home")

templates/about.html
{% extends "layout.html" %}

{% block title %}
    About
{% endblock title %}

{% block main %}
    <h1>About</h1>
{% endblock main %}

templates/article-create.html
{% extends "layout.html" %}

{% block title %}
    Create Article
{% endblock title %}

{% block main %}
    <h1>Create Article</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button class="btn">Create</button>
    </form>
{% endblock main %}

templates/article-detail.html
{% extends "layout.html" %}

{% block title %}
    Article Detail
{% endblock title %}

{% block main %}

    {% if article.image %}
        <img src="{{article.image.url}}" alt="">
    {% endif %}
    <p>{{article.author}} | {{ article.created_date }}</p>
    <h2>{{ article.title }}</h2>
    <p>{{ article.content|safe }}</p>

    
    {% if comments %}
        <h2>Comments</h2>
        <div class="comments">
            {% for comment in comments %}
                <h3>{{comment.author}} | {{comment.date}}</h3>
                <p>{{comment.content}}</p>
            {% endfor %}
        </div>
    {% else %}
        <p>No comments</p>
    {% endif %}
    <br>

    
    <form action="{% url 'article:comment-create' article.id %}" method="post">
        {% csrf_token %}

        <div class="form-group">
            <label for="comment-author">Author</label>
            <input type="text" name="comment_author" id="comment-author">
        </div>
        <div class="form-group">
            <label for="comment-content">Content</label>
            <textarea type="text" name="comment_content" id="comment-content" rows="10" cols="50"></textarea>
        </div>

        <button type="submit" class="btn">Add comment</button>
    </form>
{% endblock main %}

templates/article-update.html
{% extends "layout.html" %}

{% block title %}
    Update Article
{% endblock title %}

{% block main %}
    <h1>Update Article</h1>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button class="btn">Update</button>
    </form>
{% endblock main %}

templates/articles_list.html
{% extends "layout.html" %}

{% block title %}
    Articles
{% endblock title %}

{% block main %}
    <h1>Articles</h1>
    <br>

    <form>
        {% csrf_token %}
        <input name="keyword" type="text" placeholder="Search">
        <button type="submit" class="btn">Search</button>
    </form>

    {% if articles %}
        <ul>
            {% for article in articles %}
                <li>
                    <h3><a href="{% url 'article:detail' article.id %}">{{ article.title }}</a></h3>
                    <p>{{article.author}} | {{ article.created_date }}</p>
                    <br>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <h3>No articles</h3>
    {% endif %}

{% endblock main %}

templates/dashboard.html
{% extends "layout.html" %}

{% block title %}
    My Articles
{% endblock title %}

{% block main %}

    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success' %}
                <div class="alert alert-success">{{message}}</div>
            {% else %}
                <div class="alert alert-warning">{{message}}</div>
            {% endif %}
        {% endfor %}
    {% endif %}

    <h1>My Articles</h1>
    <a href="{% url 'article:create' %}">Create new Article</a>
    <br><br>

    <ul>
        {% for article in articles %}
            <li>
                <h3><a href="{% url 'article:detail' article.id %}">{{ article.title }}</a></h3>
                <p>{{ article.content|safe|truncatechars:50 }}</p>
                <p>{{ article.created_date }}</p>
                <a href="{% url 'article:update' article.id %}"><i class="fa-solid fa-pen"></i></a>
                <a href="{% url 'article:delete' article.id %}"><i class="fa-solid fa-trash"></i></a>
                <br>
            </li>
        {% endfor %}
    </ul>
{% endblock main %}

templates/index.html
{% extends "layout.html" %}

{% block title %}
    Home
{% endblock title %}

{% block main %}

    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success' %}
                <div class="alert alert-success">{{message}}</div>
            {% else %}
                <div class="alert alert-warning">{{message}}</div>
            {% endif %}
        {% endfor %}
    {% endif %}

    <h1>Home</h1>
{% endblock main %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            My site
        {% endblock title %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav>
            <div class="container">
                <div class="navbar">
                    <div class="nav-logo">
                        <i>Logo</i>
                    </div>
                    <div class="nav-links">
                        <ul>
                            <li><a href="{% url 'home' %}">Home</a></li>
                            <li><a href="{% url 'about' %}">About</a></li>

                            {% if user.is_authenticated %}
                                <li><a href="{% url 'article:list' %}">Articles</a></li>
                                <li><a href="{% url 'article:dashboard' %}"><i class="fa-regular fa-user"></i></a></li>
                                <li><a href="{% url 'user:logout' %}"><i class="fa-solid fa-right-from-bracket"></i></a></li>
                            {% else %}
                                <li><a href="{% url 'user:login' %}">Login</a></li>
                                <li><a href="{% url 'user:register' %}">Register</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <main>
        <div class="container">
            {% block main %}
                Nothing here
            {% endblock main %}
        </div>
    </main>
</body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block title %}
    Login
{% endblock title %}

{% block main %}
    <h1>Login</h1>

    <form method="post">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="{{form.username.id_for_label}}">Username</label>
            {{form.username}}
        </div>
        <div class="form-group">
            <label for="{{form.password.id_for_label}}">Password</label>
            {{form.password}}
        </div>

        <button class="btn">Login</button>
    </form>
{% endblock main %}

templates/register.html
{% extends "layout.html" %}

{% block title %}
    Register
{% endblock title %}

{% block main %}
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn">Register</button>
    </form>
{% endblock main %}